# Generated by Django 3.2.10 on 2021-12-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(default='watches.jpg', max_length=100),
        ),
    ]
