# Generated by Django 3.2.10 on 2021-12-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211220_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.FileField(upload_to='products/static/images'),
        ),
    ]
